# Generated by Django 4.2.4 on 2023-10-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediator',
            options={'ordering': ['create_at']},
        ),
    ]
