# Generated by Django 4.2.4 on 2023-10-05 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_deleted_user_deleted_at_user_profile_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediator",
            options={"ordering": ["create_at"]},
        ),
    ]
