# Generated by Django 4.2.4 on 2023-10-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_deleted_user_deleted_at_user_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediator',
            options={'ordering': ['create_at']},
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='summary',
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='mediator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='get_info', serialize=False, to='user.mediator'),
        ),
    ]
