# Generated by Django 4.2.4 on 2023-10-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_mediator_options'),
        ('user', '0003_alter_mediator_options_remove_additionalinfo_photo_and_more'),
    ]

    operations = [
    ]
