# Generated by Django 4.2.4 on 2023-09-09 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_documenttype_basicuser_mediator_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_code', models.CharField(max_length=128, unique=True, verbose_name='Approve code')),
                ('code_expiration_date', models.DateTimeField(verbose_name='code expiration date')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved?')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='email_confirmation',
                                      to=settings.AUTH_USER_MODEL, verbose_name='email confirmation')),
            ],
        ),
    ]
