# Generated by Django 4.2.4 on 2023-09-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_emailconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
