# Generated by Django 4.2.5 on 2023-09-21 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_remove_user_photo_remove_user_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInfo",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mediator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="add_info_for_mediator",
                        serialize=False,
                        to="user.mediator",
                    ),
                ),
                ("rate", models.IntegerField(blank=True, null=True)),
                (
                    "photo",
                    models.FilePathField(
                        blank=True, null=True, path="mediators_photo/"
                    ),
                ),
                ("summary", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("user.mediator",),
        ),
    ]
