# Generated by Django 4.2.4 on 2023-10-06 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("scheduled_date", models.DateTimeField()),
                (
                    "file_path",
                    models.FilePathField(blank=True, null=True, path="conflicts_doc/"),
                ),
            ],
        ),
    ]
