# Generated by Django 4.2.4 on 2023-10-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conflict", "0001_initial"),
        ("conference", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferences",
            name="conflict_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="conflict.conflict"
            ),
        ),
    ]
