# Generated by Django 4.2.4 on 2023-09-09 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('status', models.TextField(choices=[('В работе', 'In Process'), ('Завершен', 'Closed'), ('Новый', 'New'), ('Черновик', 'Draft')], default='Черновик')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_all_visible', models.BooleanField(default=False, verbose_name='Доступно для всех?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('closed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conflict',
                'verbose_name_plural': 'Conflict',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.FileField(null=True, upload_to='documents_users')),
                ('is_all_visible', models.BooleanField(default=False, verbose_name='Виден всем?')),
                ('conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='conflict.conflict', verbose_name='Обращение')),
            ],
        ),
    ]
