# Generated by Django 4.2.4 on 2023-10-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('status', models.TextField(choices=[('В работе', 'В работе'), ('Завершен', 'Завершен'), ('Новый', 'Новый'), ('Черновик', 'Черновик')], default='Черновик', verbose_name='Статус')),
                ('category', models.TextField(choices=[('не выбрано', 'не выбрано'), ('корпоративный', 'корпоративный'), ('бизнес', 'бизнес'), ('семейный', 'семейный'), ('недвижимость', 'недвижимость'), ('наследство', 'наследство'), ('личный', 'личный')], default='не выбрано', verbose_name='Категория')),
                ('mediators_level', models.TextField(choices=[('не выбрано', 'не выбрано'), ('новичок', 'новичок'), ('бывалый', 'бывалый'), ('дорогой', 'дорогой'), ('уровень Бог', 'уровень Бог')], default='не выбрано', verbose_name='Уровень медиатора')),
                ('prise', models.TextField(choices=[('не выбрано', 'не выбрано'), ('низкая', 'низкая'), ('средняя', 'средняя'), ('высокая', 'высокая')], default='не выбрано', verbose_name='Цена')),
                ('fixed_price', models.CharField(max_length=256, null=True, verbose_name='Цена')),
                ('decide_time', models.TextField(choices=[('не выбрано', 'не выбрано'), ('1 День', '1 День'), ('2 Дня', '2 Дня'), ('3 Дня', '3 Дня'), ('1 Неделя', '1 Неделя')], default='не выбрано', verbose_name='Время на решение')),
                ('country', models.CharField(max_length=256, null=True, verbose_name='Страна')),
                ('city', models.CharField(max_length=256, null=True, verbose_name='Город')),
                ('language', models.CharField(max_length=256, null=True, verbose_name='Язык')),
                ('language_level', models.TextField(choices=[('A1', ' A1 — Уровень выживания (Survival Level: Beginner и Elementary)'), ('A2', ' A2 — Предпороговый уровень (Waystage: Pre-Intermediate)'), ('B1', ' B1 — Пороговый уровень (Threshold: Intermediate)'), ('B2', ' B2 — Пороговый продвинутый уровень (Vantage: Upper-Intermediate)'), ('C1', ' C1 — Уровень профессионального владения (Effective Operational Proficiency: Advanced)'), ('C2', ' C2 — Уровень владения в совершенстве (Mastery: Proficiency)')], default='A1', verbose_name='Уровень владения языком')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок обращения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_all_visible', models.BooleanField(default=False, verbose_name='Доступно для всех?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('closed_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conflicts', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('mediator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownable_conflicts', to=settings.AUTH_USER_MODEL, verbose_name='Медиатор')),
                ('respondents', models.ManyToManyField(related_name='conflicts_as_respondent', to=settings.AUTH_USER_MODEL, verbose_name='Остальные участники')),
            ],
            options={
                'verbose_name': 'Conflict',
                'verbose_name_plural': 'Conflict',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.FileField(null=True, upload_to='documents_users')),
                ('is_all_visible', models.BooleanField(default=False, verbose_name='Виден всем?')),
                ('conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='conflict.conflict', verbose_name='Обращение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
