# Generated by Django 4.2.4 on 2023-09-09 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conflict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conflicts', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='mediator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownable_conflicts', to=settings.AUTH_USER_MODEL, verbose_name='Медиатор'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='respondents',
            field=models.ManyToManyField(blank=True, null=True, related_name='conflicts_as_respondent', to=settings.AUTH_USER_MODEL, verbose_name='Остальные участники'),
        ),
    ]
