# Generated by Django 4.2.4 on 2023-09-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conflict',
            options={'ordering': ('-created',), 'verbose_name': 'Conflict', 'verbose_name_plural': 'Conflict'},
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
