# Generated by Django 4.2.4 on 2023-10-03 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conflict', '0002_remove_conflict_is_all_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='is_all_visible',
            field=models.BooleanField(default=False, verbose_name='Доступно для всех?'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='language',
            field=models.CharField(max_length=256, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='language_level',
            field=models.TextField(choices=[('A1', ' A1 — Уровень выживания (Survival Level: Beginner и Elementary)'), ('A2', ' A2 — Предпороговый уровень (Waystage: Pre-Intermediate)'), ('B1', ' B1 — Пороговый уровень (Threshold: Intermediate)'), ('B2', ' B2 — Пороговый продвинутый уровень (Vantage: Upper-Intermediate)'), ('C1', ' C1 — Уровень профессионального владения (Effective Operational Proficiency: Advanced)'), ('C2', ' C2 — Уровень владения в совершенстве (Mastery: Proficiency)')], default='A1', verbose_name='Уровень владения языком'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='mediators_level',
            field=models.TextField(choices=[('не выбрано', 'не выбрано'), ('новичок', 'новичок'), ('бывалый', 'бывалый'), ('дорогой', 'дорогой'), ('уровень Бог', 'уровень Бог')], default='не выбрано', verbose_name='Уровень медиатора'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='prise',
            field=models.TextField(choices=[('не выбрано', 'не выбрано'), ('низкая', 'низкая'), ('средняя', 'средняя'), ('высокая', 'высокая')], default='не выбрано', verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='respondents',
            field=models.ManyToManyField(related_name='conflicts_as_respondent', to=settings.AUTH_USER_MODEL, verbose_name='Остальные участники'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='status',
            field=models.TextField(choices=[('В работе', 'В работе'), ('Завершен', 'Завершен'), ('Новый', 'Новый'), ('Черновик', 'Черновик')], default='Черновик', verbose_name='Статус'),
        ),
    ]
