# Generated by Django 4.2.4 on 2023-09-09 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conflict', '0002_alter_conflict_options_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.FileField(null=True, upload_to='documents_users')),
                ('is_all_visible', models.BooleanField(default=False, verbose_name='Виден всем?')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='body_as_markdown',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='concluded_contract',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='description_as_visible',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='personal_data_processed',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='respect_confidentiality',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='respondent',
        ),
        migrations.AddField(
            model_name='conflict',
            name='is_all_visible',
            field=models.BooleanField(default=False, verbose_name='Доступно для всех?'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='respondents',
            field=models.ManyToManyField(blank=True, null=True, related_name='conflicts_as_respondent',
                                         to=settings.AUTH_USER_MODEL, verbose_name='Остальные участники'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conflicts',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='mediator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ownable_conflicts', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Медиатор'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='status',
            field=models.TextField(
                choices=[('В работе', 'In Process'), ('Завершен', 'Closed'), ('Новый', 'New'), ('Черновик', 'Draft')],
                default='Черновик'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='document',
            name='conflict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='files', to='conflict.conflict', verbose_name='Обращение'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
