# Generated by Django 4.2.4 on 2023-09-11 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conflict", "0003_document_delete_documenttype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conflict",
            name="respondents",
            field=models.ManyToManyField(
                related_name="conflicts_as_respondent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Остальные участники",
            ),
        ),
    ]
