# Generated by Django 4.2.4 on 2023-10-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0004_remove_conflict_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflict',
            name='mediators_level',
        ),
    ]
