# Generated by Django 4.2.4 on 2023-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0004_conflict_category_alter_conflict_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='city',
            field=models.CharField(max_length=256, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='country',
            field=models.CharField(max_length=256, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='decide_time',
            field=models.TextField(choices=[('не выбрано', 'не выбрано'), ('1 День', '1 День'), ('2 Дня', '2 Дня'), ('3 Дня', '3 Дня'), ('1 Неделя', '1 Неделя')], default='не выбрано', verbose_name='Время на решение'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='fixed_price',
            field=models.CharField(max_length=256, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='language',
            field=models.CharField(max_length=256, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='language_level',
            field=models.CharField(max_length=256, null=True, verbose_name='Уровень владения языком'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='prise',
            field=models.TextField(choices=[('не выбрано', 'не выбрано'), ('низкая', 'низкая'), ('средняя', 'средняя'), ('высокая', 'высокая')], default='не выбрано', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='category',
            field=models.TextField(choices=[('не выбрано', 'не выбрано'), ('корпоративный', 'корпоративный'), ('бизнес', 'бизнес'), ('семейный', 'семейный'), ('недвижимость', 'недвижимость'), ('наследство', 'наследство'), ('личный', 'личный')], default='не выбрано', verbose_name='Категория'),
        ),
    ]
