# Generated by Django 4.2.4 on 2023-09-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0005_conflict_city_conflict_country_conflict_decide_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='mediators_level',
            field=models.TextField(choices=[('не выбрано', 'не выбрано'), ('новичок', 'новичок'), ('бывалый', 'бывалый'), ('дорогой', 'дорогой'), ('уровень Бог', 'уровень Бог')], default='не выбрано', verbose_name='Уровень медиатора'),
        ),
    ]
