# Generated by Django 4.2.4 on 2023-10-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0005_remove_conflict_mediators_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflict',
            name='prise',
        ),
    ]
