# Generated by Django 4.2.4 on 2023-09-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conflict", "0007_alter_conflict_language_level_alter_conflict_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conflict",
            name="language_level",
            field=models.TextField(
                choices=[
                    (
                        "A1",
                        " A1 — Уровень выживания (Survival Level: Beginner и Elementary)",
                    ),
                    ("A2", " A2 — Предпороговый уровень (Waystage: Pre-Intermediate)"),
                    ("B1", " B1 — Пороговый уровень (Threshold: Intermediate)"),
                    (
                        "B2",
                        " B2 — Пороговый продвинутый уровень (Vantage: Upper-Intermediate)",
                    ),
                    (
                        "C1",
                        " C1 — Уровень профессионального владения (Effective Operational Proficiency: Advanced)",
                    ),
                    (
                        "C2",
                        " C2 — Уровень владения в совершенстве (Mastery: Proficiency)",
                    ),
                ],
                default="A1",
                verbose_name="Уровень владения языком",
            ),
        ),
    ]
