# Generated by Django 4.2.4 on 2023-10-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0007_remove_conflict_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflict',
            name='is_all_visible',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='respondents',
        ),
    ]
