# Generated by Django 4.2.4 on 2023-10-03 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conflict', '0008_remove_conflict_is_all_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='mediator',
            field=models.ForeignKey(blank=True, default='Не выбран', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownable_conflicts', to=settings.AUTH_USER_MODEL, verbose_name='Медиатор'),
        ),
    ]
