# Generated by Django 4.2.4 on 2023-10-04 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conflict', '0010_alter_conflict_mediator'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='respondents',
            field=models.ManyToManyField(blank=True, null=True, related_name='conflicts_as_respondent', to=settings.AUTH_USER_MODEL, verbose_name='Остальные участники'),
        ),
    ]
