# Generated by Django 4.2.4 on 2023-10-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflict', '0011_conflict_respondents'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='status',
            field=models.TextField(choices=[('В работе', 'В работе'), ('Завершен', 'Завершен'), ('Новый', 'Новый'), ('Черновик', 'Черновик')], default='Новый', null=True, verbose_name='Статус'),
        ),
    ]
